Repository Simplon-hdf/Projet-DotNet-P6-LJMA, pull requests merged in 2024-08, with the labels that each got.

#25 Feat/back/t 14
  Projet-DotNet-P6-LJMA/Program.cs
  Projet-DotNet-P6-LJMA/Repositories/Interfaces/IRandonneeRepository.cs
  Projet-DotNet-P6-LJMA/Repositories/RandonneeRepository.cs
Labels: enhancement

#37 Feat/back/t 41
  Projet-DotNet-P6-LJMA/Controllers/ThemesController.cs
  Projet-DotNet-P6-LJMA/Data/ApiDbContext.cs
  Projet-DotNet-P6-LJMA/Mapping/Mapper.cs
  Projet-DotNet-P6-LJMA/Models/Theme.cs
  Projet-DotNet-P6-LJMA/ModelsDTO/ThemeDTO.cs
  Projet-DotNet-P6-LJMA/Program.cs
  Projet-DotNet-P6-LJMA/Services/Interfaces/IThemeService.cs
  Projet-DotNet-P6-LJMA/Services/ThemeService.cs
Labels: enhancement

#43 Feat/back/t 44
  Projet-DotNet-P6-LJMA/Controllers/VlogsController.cs
  Projet-DotNet-P6-LJMA/Data/ApiDbContext.cs
  Projet-DotNet-P6-LJMA/Mapping/Mapper.cs
  Projet-DotNet-P6-LJMA/Models/Vlog.cs
  Projet-DotNet-P6-LJMA/ModelsDTO/VlogCreatedDto.cs
  Projet-DotNet-P6-LJMA/ModelsDTO/VlogDto.cs
  Projet-DotNet-P6-LJMA/Program.cs
  Projet-DotNet-P6-LJMA/Repositories/Interfaces/IVlogRepository.cs
  Projet-DotNet-P6-LJMA/Repositories/VlogRepository.cs
  Projet-DotNet-P6-LJMA/Services/Interfaces/IVlogService.cs
  Projet-DotNet-P6-LJMA/Services/VlogService.cs
Labels: enhancement

#39 Feat/back/t 42
  Projet-DotNet-P6-LJMA/Controllers/SessionsController.cs
  Projet-DotNet-P6-LJMA/Data/ApiDbContext.cs
  Projet-DotNet-P6-LJMA/Mapping/Mapper.cs
  Projet-DotNet-P6-LJMA/Models/Session.cs
  Projet-DotNet-P6-LJMA/ModelsDTO/SessionDTO.cs
  Projet-DotNet-P6-LJMA/Program.cs
  Projet-DotNet-P6-LJMA/Services/Interfaces/ISessionService.cs
  Projet-DotNet-P6-LJMA/Services/SessionService.cs
Labels: enhancement

#40 refactor(ThemesController.cs): Fix type of parameter for create method
  Projet-DotNet-P6-LJMA/Controllers/ThemesController.cs
Labels: enhancement

#41 Feat/back/t 45
  Projet-DotNet-P6-LJMA/Controllers/RandonneeController.cs
  Projet-DotNet-P6-LJMA/Mapping/Mapper.cs
  Projet-DotNet-P6-LJMA/Models/Randonnee.cs
  Projet-DotNet-P6-LJMA/ModelsDTO/RandonneeDto.cs
  Projet-DotNet-P6-LJMA/Program.cs
  Projet-DotNet-P6-LJMA/Repositories/Interfaces/IRandonneeRepository.cs
  Projet-DotNet-P6-LJMA/Services/Interfaces/IRandonneeService.cs
  Projet-DotNet-P6-LJMA/Services/RandonneeService.cs
Labels: enhancement, fix

#38 feat: Création de la structure de la couche service de Reserver
  Projet-DotNet-P6-LJMA/Controllers/ReserversController.cs
  Projet-DotNet-P6-LJMA/Mapping/Mapper.cs
  Projet-DotNet-P6-LJMA/Models/Reserver.cs
  Projet-DotNet-P6-LJMA/ModelsDTO/ReserverCreatedDto.cs
  Projet-DotNet-P6-LJMA/ModelsDTO/ReserverDto.cs
  Projet-DotNet-P6-LJMA/Program.cs
  Projet-DotNet-P6-LJMA/Repositories/Interfaces/IReserverRepository.cs
  Projet-DotNet-P6-LJMA/Repositories/ReserverRepository.cs
  Projet-DotNet-P6-LJMA/Services/Interfaces/IReserverService.cs
  Projet-DotNet-P6-LJMA/Services/ReserverService.cs
Labels: enhancement

#42 Fix des Type Guid, points d'entrée de l'api Utilisateur
  Projet-DotNet-P6-LJMA/Controllers/UtilisateursController.cs
  Projet-DotNet-P6-LJMA/Models/Utilisateur.cs
  Projet-DotNet-P6-LJMA/Repositories/UtilisateurRepository.cs
Labels: fix

#45 Fix(RandonneeRepository.cs): correction de la méthode DeleteAsync
  Projet-DotNet-P6-LJMA/Repositories/RandonneeRepository.cs
Labels: fix

#47 refactor(ApiDbContext.cs): fix name of foreign keys
  Projet-DotNet-P6-LJMA/Data/ApiDbContext.cs
Labels: fix

#54 Feat/back/t 51
  Projet-DotNet-P6-LJMA/Controllers/VlogsController.cs
  Projet-DotNet-P6-LJMA/Mapping/Mapper.cs
  Projet-DotNet-P6-LJMA/ModelsDTO/VlogCreatedDto.cs
  Projet-DotNet-P6-LJMA/Repositories/VlogRepository.cs
Labels: fix

#50 fix(ThemesController.cs): fix GetId method
  Projet-DotNet-P6-LJMA/Controllers/ThemesController.cs
  Projet-DotNet-P6-LJMA/Repositories/ThemeRepository.cs
Labels: fix

#51 fix(SessionsController.cs): fix GetId ^& Put methods
  Projet-DotNet-P6-LJMA/Controllers/SessionsController.cs
Labels: fix

#52 Feat/back/t 50
  Projet-DotNet-P6-LJMA/Controllers/ReserversController.cs
  Projet-DotNet-P6-LJMA/Mapping/Mapper.cs
  Projet-DotNet-P6-LJMA/ModelsDTO/ReserverCreatedDto.cs
  Projet-DotNet-P6-LJMA/Repositories/ReserverRepository.cs
Labels: fix

#53 Feat/back/t 52
  Projet-DotNet-P6-LJMA/Controllers/RandonneeController.cs
  Projet-DotNet-P6-LJMA/Models/Randonnee.cs
  Projet-DotNet-P6-LJMA/ModelsDTO/RandonneeDto.cs
  Projet-DotNet-P6-LJMA/Repositories/RandonneeRepository.cs
Labels: fix

#59 feat: ajout des configuration pour le backOffice
  Projet-DotNet-P6-LJMA/Infrastructure/Configurations/ApplicationSetup.cs
Labels: enhancement

#60 hotfix: récuperation du role pour ClaimTypes.Role de la classe JwtHelper
  Projet-DotNet-P6-LJMA/Modules/AuthentificationModule/Repositories/AuthentificationRepository.cs
  Projet-DotNet-P6-LJMA/Modules/UtilisateurModule/Services/UtilisateurService.cs
  Projet-DotNet-P6-LJMA/Shared/DTOs/AuthentificateDTO.cs
Labels: fix

#64 fix : migration pour mac
  Projet-DotNet-P6-LJMA/Data/ApiDbContext.cs
  Projet-DotNet-P6-LJMA/Data/DataSeeder.cs
  Projet-DotNet-P6-LJMA/Infrastructure/Configurations/DataInitializer.cs
  Projet-DotNet-P6-LJMA/Infrastructure/Configurations/DatabaseConfiguration.cs
  Projet-DotNet-P6-LJMA/Infrastructure/Configurations/ServiceCollectionExtensions.cs
  Projet-DotNet-P6-LJMA/Infrastructure/Data/README.md
  Projet-DotNet-P6-LJMA/Models/Post.cs
  Projet-DotNet-P6-LJMA/Models/Randonnee.cs
  Projet-DotNet-P6-LJMA/Models/Reserver.cs
  Projet-DotNet-P6-LJMA/Models/Session.cs
  Projet-DotNet-P6-LJMA/Models/Theme.cs
  Projet-DotNet-P6-LJMA/Models/Utilisateur.cs
  Projet-DotNet-P6-LJMA/Models/Vlog.cs
  Projet-DotNet-P6-LJMA/Modules/AuthentificationModule/Repositories/AuthentificationRepository.cs
  Projet-DotNet-P6-LJMA/Modules/AuthentificationModule/Repositories/IAuthentificationRepository.cs
  Projet-DotNet-P6-LJMA/Modules/AuthentificationModule/Services/AuthentificationService.cs
  Projet-DotNet-P6-LJMA/Modules/PostModule/Repositories/IPostRepository.cs
  Projet-DotNet-P6-LJMA/Modules/PostModule/Repositories/PostRepository.cs
  Projet-DotNet-P6-LJMA/Modules/PostModule/Services/PostService.cs
  Projet-DotNet-P6-LJMA/Modules/RandonneeModule/Repositories/IRandonneeRepository.cs
  Projet-DotNet-P6-LJMA/Modules/RandonneeModule/Repositories/RandonneeRepository.cs
  Projet-DotNet-P6-LJMA/Modules/RandonneeModule/Services/RandonneeService.cs
  Projet-DotNet-P6-LJMA/Modules/ReserverModule/Repositories/IReserverRepository.cs
  Projet-DotNet-P6-LJMA/Modules/ReserverModule/Repositories/ReserverRepository.cs
  Projet-DotNet-P6-LJMA/Modules/ReserverModule/Services/ReserverService.cs
  Projet-DotNet-P6-LJMA/Modules/SessionModule/Repositories/ISessionRepository.cs
  Projet-DotNet-P6-LJMA/Modules/SessionModule/Repositories/SessionRepository.cs
  Projet-DotNet-P6-LJMA/Modules/SessionModule/Services/SessionService.cs
  Projet-DotNet-P6-LJMA/Modules/ThemeModule/Repositories/IThemeRepository.cs
  Projet-DotNet-P6-LJMA/Modules/ThemeModule/Repositories/ThemeRepository.cs
  Projet-DotNet-P6-LJMA/Modules/ThemeModule/Services/ThemeService.cs
  Projet-DotNet-P6-LJMA/Modules/UtilisateurModule/Repositories/IUtilisateurRepository.cs
  Projet-DotNet-P6-LJMA/Modules/UtilisateurModule/Repositories/UtilisateurRepository.cs
  Projet-DotNet-P6-LJMA/Modules/UtilisateurModule/Services/UtilisateurService.cs
  Projet-DotNet-P6-LJMA/Modules/VlogModule/Repositories/IVlogRepository.cs
  Projet-DotNet-P6-LJMA/Modules/VlogModule/Repositories/VlogRepository.cs
  Projet-DotNet-P6-LJMA/Modules/VlogModule/Services/VlogService.cs
  Projet-DotNet-P6-LJMA/Shared/Mapping/Mapper.cs
Labels: fix
